config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles
end

app/views/articles/edit.html.erb
<%= render "shared/form" %>

app/views/articles/index.html.erb
<h1>Liste de tous nos articles</h1>

<% @articles.each do |article| %>

  <h2>Titre de l'article : <%= article.titre %></h2>
  <p>Description:<%= article.description%></p>
  <p> Article ecrit par : <%= article.auteur%></p>
  <%= link_to "Lire l'article", show_article_path(article), class: "btn btn-primary" %>
  <%= link_to "Modifier l'article", edit_article_path(article), class: "btn btn-secondary" %>
  <%= link_to "Supprimer l'article", destroy_article_path(article), class: "btn btn-danger", method: :delete ,data:{confirm: "Etes vous sur ?"} %>



<% end %>

app/views/articles/new.html.erb
<h1>Creer un article</h1>
<%= render "shared/form" %>

app/views/articles/show.html.erb
  <h1><%=@article.titre%></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <div style="margin:5%">

    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_for :article do |f| %>
<div class="form-group">
  <%= f.label  :titre %>
  <br>
  <%= f.text_field  :titre, placeholder:"Titre de l'article", class: "form-control"%>
  <br>
  <%= f.label  :description %>
  <br>
  <%= f.text_field  :description, class: "form-control"%>
  <br>
  <%= f.label  :contenu %>
  <br>
  <%= f.text_area :contenu, class: "form-control" %>
  <br>
  <%= f.label :auteur %>
  <br>
  <%= f.text_field :auteur, class: "form-control" %>
  <br>
  <%= f.submit "Modifier l'article", class: "btn btn-primary" %>
  <br>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
     <a class="navbar-brand" href="#">Navbar</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse" id="navbarsExampleDefault">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item active">
         <%= link_to "Acceuil", articles_path, class: "nav-link" %>
         </li>
         <li class="nav-item">
           <%= link_to "Creer", new_article_path, class: "nav-link" %>
         </li>
           </div>
         </li>
       </ul>
     </div>
   </nav>